### ISSUE TITLE
KeyError: 'set_dns 第二参数错误：s3-1-w.amazonaws.com'

### ISSUE THREAD

**Issue by miketwes** [SeaHOH/GotoX#108]
Github上传图像提示:

GotoX/local/ProxyHandler.py", line 191, in handle_one_request
    self.do_METHOD()
  File "GotoX/local/ProxyAuthHandler.py", line 297, in do_METHOD
    AutoProxyHandler.do_METHOD(self)
  File "GotoX/local/ProxyHandler.py", line 314, in do_METHOD
    self.do_action()
  File "GotoX/local/ProxyHandler.py", line 218, in do_action
    self.hostname = hostname = set_dns(self.host, iporname)
  File "GotoX/local/common/dns.py", line 57, in set_dns
    raise KeyError('set_dns 第二参数错误：' + iporname)
KeyError: 'set_dns 第二参数错误：s3-1-w.amazonaws.com'

**Comment by SeaHOH** [comment]
你的 DNS 解析有问题吧，前面的日志难道没提示？

**Comment by miketwes** [comment]
Exception happened during processing of request from ('127.0.0.1', 50818)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "GotoX/local/ProxyServer.py", line 116, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "GotoX/local/ProxyHandler.py", line 132, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "GotoX/local/ProxyHandler.py", line 189, in handle_one_request
    self.do_CONNECT()
  File "GotoX/local/ProxyAuthHandler.py", line 293, in do_CONNECT
    AutoProxyHandler.do_CONNECT(self)
  File "GotoX/local/ProxyHandler.py", line 288, in do_CONNECT
    self.do_action()
  File "GotoX/local/ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "GotoX/local/ProxyHandler.py", line 1073, in do_FAKECERT
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "GotoX/local/ProxyHandler.py", line 191, in handle_one_request
    self.do_METHOD()
  File "GotoX/local/ProxyAuthHandler.py", line 297, in do_METHOD
    AutoProxyHandler.do_METHOD(self)
  File "GotoX/local/ProxyHandler.py", line 314, in do_METHOD
    self.do_action()
  File "GotoX/local/ProxyHandler.py", line 218, in do_action
    self.hostname = hostname = set_dns(self.host, iporname)
  File "GotoX/local/common/dns.py", line 57, in set_dns
    raise KeyError('set_dns 第二参数错误：' + iporname)
KeyError: 'set_dns 第二参数错误：s3-1-w.amazonaws.com'

4:25:35 W L4:50900-> do_FORWARD 连接远程主机 ('r1---sn-vgqsrnee.gvt1.com', 443) 失败，尝试使用 "FAKECERT & GAE" 规则。
14:25:35 W 将 'https://r1---sn-vgqsrnee.gvt1.com' 加入 "GAE" 规则 15 分钟

**Comment by SeaHOH** [comment]
你需要设置 `debuginfo` 来查看更多日志信息。

**Comment by SeaHOH** [comment]
话说你不能在 shell 里自己解析下试试？

**Comment by miketwes** [comment]
```
    @^github.+s3.amazonaws.com$ = s3-1-w.amazonaws.com
    @^github.+s3.amazonaws.com$ = s3-1-w.amazonaws.com
```

注释GotoX/config/ActionFilter.ini 第97行,第122行以后上传正常:

![2019-03-07_321x595](https://user-images.githubusercontent.com/6849681/53938085-07450700-40ea-11e9-8b7d-6a5f197840b6.png)

**Comment by SeaHOH** [comment]
你这样做能正常也可以，反正规则随便写，适用就好。
