### ISSUE TITLE
有些网站打不开

### ISSUE THREAD

**Issue by kxmp** [SeaHOH/GotoX#120]
是https的
比如https://imgur.com/
我用的master最新分支那个.....

**Comment by SeaHOH** [comment]
看置顶贴

**Comment by kxmp** [comment]
我用的全局代理的...
dns里面还用的不会被污染的dns
能开其他被封网站

**Comment by kxmp** [comment]
天哪 从没用过这个 我学习下去.
为什么某些网站就要伪造sni呢...!!!!!
我真是服了 我发现i.imgur.com没什么问题 为什么主站就打不开呢!!

**Comment by kxmp** [comment]
日志来了 浏览器访问还没什么日志 curl拉了一下日志变多了
```
19:33:18 W L4:58421->xxx.xxx.xxx.xxx do_GAE "GET https://imgur.com/" 返回：OSError(
"Not a gzipped file (b'co')",)，重试
19:33:19 E L4:58421->xxx.xxx.xxx.xxx do_GAE "GET https://imgur.com/" 失败：OSError(
"Not a gzipped file (b'co')",)
Traceback (most recent call last):
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 818, in do_GAE
    response, data, need_chunked = self.handle_response_headers(response)
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 461, in handle_resp
onse_headers
    data = response.read(self.bufsize)
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 463, in read
  File "gzip.py", line 411, in _read_gzip_header
OSError: Not a gzipped file (b'co')
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58421)
Traceback (most recent call last):
  File "socketserver.py", line 654, in process_request_thread
  File "D:\Program\GotoX-master\local\ProxyServer.py", line 113, in finish_reque
st
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 131, in __init__
    self.handle()
  File "http\server.py", line 418, in handle
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 188, in handle_one_
request
    self.do_CONNECT()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 1393, in do_CONNECT

    self.do_action()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 231, in do_action
    getattr(self, self.action)()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 1067, in do_FAKECER
T
    self.handle()
  File "http\server.py", line 418, in handle
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 190, in handle_one_
request
    self.do_METHOD()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 1400, in do_METHOD
    self.do_action()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 231, in do_action
    getattr(self, self.action)()
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 855, in do_GAE
    errors.append(last_response.read().decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 48: invalid
 start byte
----------------------------------------

```

**Comment by kxmp** [comment]
我用ie访问了下 ping.eu还是那样就1行也没说明什么
imgur的时候日志出来了
```
19:40:47 W L4:58880-> do_GAE "GET https://imgur.com/" 返回：error('Error -3 whil
e decompressing data: invalid stored block lengths',)，重试
19:40:49 E L4:58880-> do_GAE "GET https://imgur.com/" 失败：error('Error -3 whil
e decompressing data: invalid stored block lengths',)
Traceback (most recent call last):
  File "D:\Program\GotoX-master\local\ProxyHandler.py", line 689, in do_GAE
    response = gae_urlfetch(self.command, self.url, request_headers, payload, ap
pid)
  File "D:\Program\GotoX-master\local\GAEFetch.py", line 211, in gae_urlfetch
    _response = _gae_urlfetch(appid, payload, request_headers, getfast, method,
realurl)
  File "D:\Program\GotoX-master\local\GAEFetch.py", line 265, in _gae_urlfetch
    raw_response_line, headers_data = zlib.decompress(data, -zlib.MAX_WBITS).spl
it(b'\r\n', 1)
zlib.error: Error -3 while decompressing data: invalid stored block lengths

```

**Comment by SeaHOH** [comment]
python 版本？

**Comment by kxmp** [comment]
我直接把你那个最新发行版里面的py复制过来用了 扔到了最新master版本目录里面...

**Comment by SeaHOH** [comment]
问一句，你的 GAE 服务端是？

**Comment by kxmp** [comment]
我这不是新部署的么 就下载了你那个url里面的
https://github.com/SeaHOH/GotoX/releases/tag/gae-r6

**Comment by SeaHOH** [comment]
怀疑你的服务端没有正确部署，请访问 https://你的appid.appspot.com/ 确认。

**Comment by SeaHOH** [comment]
还有，顺便把置顶贴的跟帖删除。

**Comment by kxmp** [comment]
访问那个显示这个
{
	"server": "goproxy r9999 (go1.9.4 (appengine-20180328), linux/amd64)"
	"latest": "2018-09-04T01:54:16Z",
	"deploy": "2019-09-11T10:01:36Z",
	"message": "already update to latest."
}

**Comment by SeaHOH** [comment]
就这两个返回 502 吗，其它有没有能正常访问的网站？

**Comment by kxmp** [comment]
我更新了最新版 重新试了下 果然不报错了 变成另一种情况了

curl拉取ping.eu 成功可以访问
但是chrome打开直接乱码了
就是网页变成了纯文本乱七八糟的东西
connection aborted. too short headers data=��Z{s�6�۞�w@عĞ�

**Comment by SeaHOH** [comment]
对哦，是乱码。重新改了一下，这回能返回可用的文本信息。

**Comment by kxmp** [comment]
从乱码变成这种东西了
connection aborted. too short headers data=b'\x08\x00\x00\x00\x00\x00\x02\xff\xadX[s\xdb\xb6\x12~\xf7\x8c\xff\x03\xc2\xf3p\xac)\xaf\xa2DI\x8c\x95\x1c\xc7v\x1a\'q\x9aS;\xb7f2\x1e\x88\\R\xb0I\x82\x05 \xc9l\x9a\xff~\x16\xa0,K\xa9\xec\xfaL\xf3"\x18\xe0\xeeb\xf7\xdb\x0bv\xfd\xe

**Comment by SeaHOH** [comment]
要的就是它，不过你没贴完整吧。
还有我上面问你，其它站点是否正常访问。

**Comment by kxmp** [comment]
完整的好长啊
ping.eu
`connection aborted. too short headers data=b'\x08\x00\x00\x00\x00\x00\x02\xff\xedZ\xfdr\xdb6\x12\xff\xdb\x9e\xf1; \xec\\bOM\x91\x94,\xcb\xd6\x873\xfePb\xb7\x8e\xadFJ;\x9d\xba\xa7\x01IHbL\x91,AZV\x9b\xcc\xdcC\xdc\x13\xde\x93\xdc.\x00~H\xb2\x1b\xb5\xb5o\xa63\x17\xc72E\x00\x8b\xc5\x0f\xbf],\x168\x1f\x0cz\x86U\xb1H\xd54\xc9\xf5\xb7[\x9b\xa7\xd4\x990\xfd4\x0c\x928\xf4\x9b$\x08u\x9e\x841\xdb\xc5\'\x07\xcbv\xc94\xe5\x89\x1e\xb3;\xea{.M\xe0E\x14\xc2\x0b(rn;&|\x8bY\xf6\x05\xc4\x85A\xc0\x9c\xc4\x0b\x83&q\xfc\x903\xf1*aA\xa2_\xb2`\x9cL\x9a\xc4\xaaV\x1b\xfb\xc5\xeb\xc1\x8b@u\xeb\x90\x98{\xcdj\xa3i6\xc8\xdbw\x83\xad\xcd\xee}\xe4\xc5\x8cg\xf5\x0e\xc9Ux\x07\x7f\x0e,b\x1e4\xeb\xd5&\x0cV\xd4\xeb\xc5t<\xa5\xcd|p[\x9b}\x16\xdf\xb1\xb8I\x8e\xa3\xec{\x02h\x84\xb7\x1et\xda;\xef\xf5\xbb\xfd\xfe\xc5Y\xc7\x1a\x1d\xd6\xdd\xbai\x1e\xda\xcc9\xb0m\xeb\xd05\xad\xbd\xfa\x1e\x1b\xb95\x97Z\x87\xb4E"\x9aL:\xc6b\xfb\xcb\xb7\x1d\x16\xb4\x08\x93\xcau\xfai\xb0K\xcc}\x1d\xc6\xa0W\xcd\xaa\xb90\x86LB\x8b\xb8\xe1\x94zA\'\xf2\x82q\x85\xa5[\x9b[\x9b\xed\x17g\xd7\xa7\x83\x1f{]r>xwIz\x1fN./N\x89\xa6\x1b\xc6\x0f\xb5S\xc38\x1b\x9c\xc9\x82\xbd\x8aI\x061\r\xb8\x87\x13@}\xc3\xe8^iG\xd0\x1eK\xc5\xdf\xee\xf1\x19\xfe}\xd7\x1d\x1cC\x93AO\xef~\xf7\xe1\xe2\xfb\x8eV\x9e\x0c\x8d\x9c^_\r\xbaW\x83\x8e\xf6\xd8\xach\xb9\x90\x80NYG\xbbe\xf3Y\x18\xbb\\#\x8e\x14\xd4\xd1P}d\n~\x86\x81\xef\x05\x8c\xc8W3f\xab\'\xfc$\x1c\xf0\xf7\x1c U\xe2MY\x98&\xf0\x10S\x87\xc5\xf0\x08/\x016\x10\xc1\x99(\xdd%\x13 \x1eTH|Y\x9d$!\xf1\xbd;(\x90\x98\xc1\xdf\x80\xef\x12\x1f\xe0O#\xe8i\x12z\xf05M<\xdfK\xe6\xa2g\xd9\xf1$I"\xf15\tC_j\x84O\xcb\xa3r\x19wb/B,K\x03\xebR>\xc7\x8eS\xd0\nZ\xea6\xe5\xcc\xcd\x86Q\x112\xa6,\xa1J\x06p\xcb\x1b\xcd\xf5;\xab$a\x12\\\xfc`\xbdg\xb3\xdb\xf3It\xe2^\xfc:\x9a\xfd\xf2\xdd\xfe\xf4\xdd\x0f\xf3\xe9\xb7w]~\xf8\xcb7\xf4\xea\xfa:\xd93\xdf\xd6\x0e:\x1a1P\xe2\xe0bp\xd9=\xba\x968\xf6\xc4 \x06%\x98\xce\xae\xfa\xf9\xa8\x7f8\xbf\xbe\xe8\xef\x92^\x18\'D\x98\xe5.y\xcf@\rP7\xab\xd2\x8b\xc3\xfb\xb9,d\xf1.9\xa1\x81;\xf3\xdcdB@q|q\xc5\x12\x98\xce[\xe2P\xdfI}\n\xfe\xa0x7\xa5|\xb1\xe04L\xc1w\xcc\x89=\'\x17\xbd]\xf2!\xf0\x12\x1c*\xf4\x08\xb2\xda\x86\xd4<\x03\x05\x91\xd7\xd9/\xa9w\xd7\xd1\xbc)\x1d3\xc4\xdd\xa6q\t\x9d \x14\x18^^\\}K\xce\xdfw\xdft4\xc3\xe1\xdc\xc0\xf9\xad\xc0\xc3\xeb\x9aF\xdew/;Z?\x99\xfb\xac?a,y\xb0>0\'\xf5\x13\x8eM\x1enpr\xdc\xef\x92I\xccF0!\xa0\x15o\x1a\x8629Q\xdc?}\x7f\xd1\x1b\x10\x9f\x06\xe3\x14\xf4\xech\xdf\xd0;\xda\x17|\xd0\x08\x8f\x1d\xe8\xe6c\xa6\xd6G\xfe\xba\xae\x1d\xb5\rI\x97?\xd0\x1aM\x0b[[\xeb\xb7\xc6\xf2\x17\xba\x8ena\x94\x06\xc2\xd3\x02\x1b\x87^\x10\xa5\xc96\xb8\xe8\x1d\xf2\xdb\xd6\xe6\xc6\x1d\x8d\xc9\x88t\xc0.\x9ct\n\xb0VFa<\xe5\x95Q\xc3G~2?\xf5)\xe7W`H\xdbD\xa3.\xb7\xe7\xe30\x1c\xfbL) Z\xbb\xde\x1d\xca\xa5>g\xe2\x1d\x0ct\x9b`\x81\x07\xaf\xcd\x16\xfciC\x0f\x15_,>\xf8\xf5\xeb\xaf\x89\xea\\\xe0\xc0\xfc\x9f\xbc\x9f+\x1e\xacZ\xb1\xf0\xa1;\x82\x89^\x90Jq\x12+\xec$k\xb4!{\xcc\x15vb\x06+\x94\xd2\x19\xf4\x84\xe2L?Q\xb7$\xbbC^\xb5\xb15G&J\xef\xaa\xc3\xa2:\x86\xb5\xd2g\xa3\x04\\\xbf\xc7\x01\xf1y\x93x\xc2\xd2u\xdb\x0f\x9d\xdb\x16\x19\x81F:\xf7~\x85%\xc5\xb2\xa2{p\xc6\xa1\x1f\xc2\x9a\xf5\x15\xb5\xe1\x87f\x15P*4M@\xa4\xd3\xd2\x8e\xce\x99\xef\x87/\xdav|tA\xe8\x94P\xc2\xa7\xd4\xf7\x89MQ\x1f\x026O.\xc8GX\xda\tZ/84F\xe3\x00$\xc5d\n\xbe\x01\x07\x15\xc6\x15l}\x92&$\r\xa0 I\x03\x18\xa9\x0f\x9e4\x99\xb0\x98\x11\x8f\x13v\xe7\xf9\x84\xbaBO"\t,$O\x18\x81\xaa\xe0OHs\xbbm\xc0\x98\x8f^\x95\x10\x11\x9aVlX1\x18\x92B\xe3!D\x16\x04F\x96\x8dH[\xa9\xac\x90\xc1\xdaelV+F\xd4uq]\x81\x8a5\x13$Z\xf0\xa1\x89J\x9f\xc5\'\x03\xa2(\xd2`#\x88Q\x02v\x15\xba\xc0\xb0$\x06\x1e\xab\x89+\xe4I\xc7\xd8Q<)\xbd\x93\x15\x95L,\x8bh\x0c\x0c@Y0\xe5\xb0\x1e$\'\x0c@\x03\xc1 lW\xb6W\xe2Q\x93\xcf\xca\x0eg^\xe0\x86\xb3\nh\xdd\xbd\x83\xe6\x97\x1e\x077\x08\xb0\xec\xa0\xf3\xbc>\xfb\x91\xd8c\xc1\xc3\x8e\xf6\xd5\xa8\xc1\x98\x03f\xa9\x88\x1d\x82\xf3\x1f\xf9\xe1L\x07&\x03)B\xdfoi\xb2]Bm\x9f\x119\xf3\x1d\xcd\xd4\x88\x80\xb2\xa3\x1d\x9a\xf066V\x87\xb0\xac\xd8\x92\xe2\xaa\x95\xd0\r\x1f\\\xf9\xb0\xd1\xa6j\xf514\x08f\x12\xd41[\x7fd\x85\x8d\xa36\xe8\xa8V\x0b\xd4\x16\x8b\x87~8\x0eQ\xe9\x1c:\xcb\xaa\x17\xd0\xd5\xf6\xb5\x92j\xb0\xa8P\xd5\xad\x91\xf5\x8b\xf0\xdc)\xec\xec0I\xc2i\x0e\x91\x1aD\x93\xa0\xdd\xe0oC\xd9\xcf\x8a\xc3\x81A\xa2g\x06\x17v\x9fX\x96\xa6F\xf4\xf7\x0bO\x16\xb1\x81\x878{\xc0I\x16\xcf\xc8(YA\x15\x97h\x96\x1b\xc0l\xe2%l\x15G\xc4\x8eT\xeb\x7f\x9e;\xf9\x1c\x0b\x8b\xc8&y\xaf\xc4j!\n\xac\xac\xe4A\xeb\xf0\xb3\xdfZ\xe5]y\xce\xf6\x1e\xb0\x9f\r\xe1\xce~\x0c\xd3\x18\x90B\xe7\xde\xb6\x8fj\xf5\x8au\xd0\xa8X\xb5j\xa5a\xb6\r\xfb\xe8\xcb\x88\xad\xa0\xb5d\xd7K\xa0eX>\xc4A\x84\xee\xb9@\\R\xe6\xabQ\x15\x7f\x1e@meRQ\xa9\xea\x83V\xa1@<\x9d\x84\xb0\xf1\xcdc\x9d\xe6\x03\x16\xa8\xc0\x8fQ\x97\x07x\x93w\x91\x89l\xe7\xc1\xa1\xf0\x0c\xe8\xe2\xf3\x00\xc4\x0e\xddye\xe4\xf90\x8d\xbc\x88R`\r\xcb*\xccb\x00\x1a\\\xfdM|\x13(\xcf#\xa9p#\xed\x978\xd6\x8d&\x9d\xd1\x8d\xf6\x11BM\xd9Y\xb3u\x93y\xa6\x1b\xed\xd8u1F\x18\xd1\xbb\x10\xa5\xf1\x9b\\\xdaF\x188\x10p\xdcB%\x88gX\x0c\xfb\xce\n\xd4~\xa3jn\xbfZ\x8a\xae_\xed\x92W\xea\x91\xe8D\xf9\x0c\xb5}z\xb5\xd3R\x81\xa8\x8a\xe8J\xdd\x14\xde\xf0F\xba\xc3\\\x17t\x877\xd94\xdfh\xd6\xfeM>\xcd\xea\x9b"\xcb\x8df\xdedh\xdfhS\x1a\x8f\xbd@2\r\x01\xd7k\xd2\xed\x95:=Z\x1e6:\xd4"\xbaS!\xc5F)v_\xb2\x0e7\xe3\xd3"\xef\x1egW\xe6zK\x14\xc8\xddu\x12F\xb8OBn\xc3\xb7ja\xb3\x7f\xcd$\x94\x95\x96{QF\xf9\x17\x16\xbc\x851\xd7\xea9\x8f\xf3\xe5\xaf\xb4\xfe!\x1b\x8cl\xd1[Y\xf5<\xf0\xd6\xdc\xa8V\x87\x824\xe5\x95\xafZ-\xcc\x19\x9f\x0b\x153Y\x1b\n\xde\xf2T\x0b\x7f\xa2\xef\xab\xb9.\xd6Z\xfb\x08\x17.\xf4q8\xc9\xe4e\xe0R\x0e\x1b\x86\xfe$\x9cq\x02\x1f\xb0\x94\r\x9e\x15\xa2\xc5\xf8\x7f\x05\xa6\xb7\xe8E\xd0m`FU\xc6\xf1\x04V\x9f\x98q\xfe4l\xc1\xed\xc6:T\xc1z\xcf\xcb\x95\xf2\xc6g\x05\x873\xd8\xfd8\x00\x05%B\x93\xa7\xf4\x9dv\xb6\xc5Z\x03\x86\xbc\xee\xb3B\xb1\xb4\xe9{\x14\x8c9\xae"n8\x13Y\x0c4\x190\x97gY]\xe4\xfeR\xc7\xad\xe5\x1a \xa9\xeaC\xac\xfe\xac8\xad\xee\x85W\xa0:UE\xb0@\xf3\xd4\x06\xcdHL\x83\xb1\xb0\xa4\xa0\xb4k~*\x98P\xd6\xba0a\xdd\xff\x1dFK\xb9\x81\xdf\x03\xaa\x0c\x0c\x02U\x06\xeeI\x80rdZB\xb7\xe7\xba\xb7\x8e;V\xf5\x87\xde\xf3\xba\xe2\x85l\xc9\xa3F\xe7\x94k\xe1\xda\x9dy\xe7\'\x82Feg\xd6\x80%\r\xbcd\x987xVh\x96\x0f\xb6\x96\xc9#K8\x11\xe7!\\9!\xd8\xda\xa2\x8a\x18\x04\xd3 \xc4\xb4\xf9\xa3\x10\xad\xa6P\xbe\x98)\xd0\xc5\xdb&\xa9\x16\x99\x82\xb6\xcc\xe7\x90\x85\xa1\xe92\xd1\xb7P1K)\x10\xca\xe7\x81\xa3\xb05":f\xd4\xadV\xe49\x0b\x94\xb8\x9e#\xe2\xf6\x8a\x13NU\xa9\xf1\x91\x1b\xa5\xc3\x98\xcaG\xbepz%d\xbf\xd0u\x91\x07$5\xd3$\x98\xbe1\x89H\'\x8bB/\xe0Y.\xaa|\xa8\xa3\xb0\xceT\xcf\xceB\x16\x8eB\xc4\xdc6A(\x0cDNn\x13dg\x19~h\xec\xd2\x84\xea\xd4\xd5\x1d\xdf\x13\xa7\x89\x0e\xd5\xa3\xd4\xd6\xf7\xaa\x8dF\xedp\xbf^o\x1c4\x0e,\xab\xb1R\x1f6\x0fP\xbb\xbe_;4\xad\xaau\xd0\xc0!\x81\x9e\x0f\xa6_\xb6KZ\x93N\x91\xa7/^~\xfaD~\xfay\xa7\x12\xa5|\xb2\xfd\xdb\xe7,]\xb0\x0c\xd2"\xa7\xf9\x84\x82\x18C\x1e\xcf\x0c\xe5\xb7J\x14\x8c\x8b\xcd\xfa\xe1A)\xd1ki\xcb@\x11\tQF\x04C2\xe1\xff\xb4\xf8?-\x1e\xa1\xc5R\xa6\xb6\x94\xf4~(\x87\xf5X\x867\xcf\x96>\x94\x11_L2/\xbb\xaf\x8c\x7fV\x91\xea\\\x9b\xa8\xcf\xc8\xd3\x82\xa6\x8d\xea\xc1\xfda\xc1\xd1\xdf\xa7\xe8\x1a\x0c\x05y\x05C\x0f\x0b\x82\xfeA~.\xd1\xf3\xe0\x10\n\xab\xa6uP]\xa0\xe7\x02;\xff$9\x97\x80\xb1\xe3\xe5\x95\xf8\x8b\xf4\xdc/\x9f\xec\xd5\xd4YQ\xce\xc2|\xa5[9[\xc9\x9bT\x9f"\xed\xbf\x9a\xd6\xcf\xa2\x04P\xef\xe8e`\xf3\xa8\xf5`\x86~\xf1x$\x0fR\xcaYr\x8dd\x19pm\x86\xbb\xf7m\xb2\x9c\xf26^\xdfwF\x83\xf1){\xb3wr\xfck\x12\xbd9\xdb\xeb\xbd9\xeet0\x15\x0e\xbf{\xa6\xb9\x8b\x1eq\x97\xa8\xffd9\r\x9e\x9f\x10\x9e\xaa\xf4I\xca\xf3#8j\x11y\n\xa7|\x97bav6!\x0f4\xf3@\xe6\xa5\x13F\xf3\xd6R\xda\x9d(=\x1f9.,A\xb5V8R2\xe7?3o\x0b]\xe4R\xe2&K\\\xb9R\x17\x90V\x87\x1c\xda\x1f1\xbc\x17#g\xc1\xf0\xed\x89\xe1\x19v\x12\xe0\xef\xd0\r\xf1\xee\xc7\xb0\xffN\xc4\xd8\xb9\xf4\x8d\xd2\xbcJ\x05a\xa74\xf5\x12\x9cE0\xde\x1e\x9d\xf7\xa8O\xfe\xf3\xaf\x7f\x93\xc1\x04\xe8FGx~\xcb(\xf7\xc0\xc5\xcf\xa8\xb8v\x02}\xab\x0b\x82\x95\x05\xb5\xc1\xcd\x08\x19\xe5\xc8}\x1d\xcd\xe3t\xf8\xfe\x03h\x0e\x13\x06\xf6w\xcf\xfc\xc5\xd3\xf2\xd2\t`\x89\x0c\x06\xb2!g\x98Q\xda\x96\xac\xb2M^\t\xa8-\xcc\xf6\xdf\xc11|\xc15\x80s(\x84\xe4\x9e`\x01\x8db;\xb7\xf1h\xb4\xf0\xa5\xf3\xe0\xbc\xa0|\x13*\x8fU\x02\xd81\xb5\xb2;n\x84\xa5q\x18\xa5>\xc7\xa3\xc2\xfe\xe0\xf8\xfd\x80\x18\x86\xbc\x95\xa2n\xc8IV\x8b[\xaa\x05\xf0\xda\x11^\xff\x1aF\\n\x9aaY\xc2\xdc\x10s\xf3kb\xe5;-J\x90\x8a\x1f h\xc1\xce\xf2^\x8d\xd7\xdcs;V\xfd\xe5G\xde\x01\xe6<\xd2\xdd\x03\xf2\x1e\xa9\x99\xdd\xdd\xc3\xf3\xdb\x07\x14\xdc\xf9\xad\xf4r\xdb\xaa\xef\xb4>om\x8a!\x97\xbb\x08\xc2\xe2\xa6 -\xdd`\x04Z\x95U\x07u\xc111 \xfa\xd0\xf6i\x00\xfe\xa5\xb4t\xff\xdeHa\x1b\xdb1s\xab3\xa5\x15vKS\xa1\x93S\x88?\xfcp\x8c\xc7bv\xbd\xab\x85,_\xbd]\x87w\xea\xc4\x83\xb8\xad\xff_8\xf6\x92_\xa91\x00\x00'`

其他网站当然正常

**Comment by kxmp** [comment]
出新情况了
现在浏览器能开17mon那个ip表地址
curl可以拉 但是发现结尾有什么奇怪东西 不像是纯文本
客户端更新的时候也报错 也是那个压缩问题
![image](https://user-images.githubusercontent.com/6483602/64754442-f625f880-d559-11e9-9d23-97ae830e5afd.png)

我还发现全局代理的时候就这个评论没法上传图片. 用的是复制到剪贴板里面的那种图片.
类似按下键盘截图键那种.
日志也是奇怪的502就一行  不知道啥情况

**Comment by SeaHOH** [comment]
始终没法重现这个编码错误，你上面说明的情况能完全重复吗，而不是相同的条件产生不同的结果。

**Comment by kxmp** [comment]
你浏览器可以开ping.eu!!?

**Comment by SeaHOH** [comment]
自定义域名吗，那你把配置改成 AppID 看能正常工作不。

我这里直连、GAE 代理 ping.eu 都正常。

**Comment by kxmp** [comment]
果然没问题
ping.eu没问题 imgur没问题
就连那个17mon列表下载也没问题.

看起来是绑定域名这地方功能有点问题了.
我那个绑定域名是个cdn的. 我也不太清楚为什么出问题了呢. 开其他压缩的页面也没问题 就ping.eu这几个有问题.

**Comment by SeaHOH** [comment]
你到 CDN 后台把缓存关掉试试。

**Comment by gxggsrmyy** [comment]
@SeaHOH  自定义域名，套cdn 后，RangeFetch 出错，视频无法播放，
提示 data_queue peek 超时，break
