### ISSUE TITLE
启动GotoX.vbs报错，请教一下是什么原因

### ISSUE THREAD

**Issue by bltcn** [SeaHOH/GotoX#123]
10:56:31 W 读取系统当前 DNS 设置失败
Traceback (most recent call last):
  File "E:\tools\GotoX\GotoX\start.py", line 9, in <module>
    from local import proxy
  File "E:\tools\GotoX\GotoX\local\proxy.py", line 90, in <module>
    from .ProxyServer import network_test, start_proxyserver
  File "E:\tools\GotoX\GotoX\local\ProxyServer.py", line 129, in <module>
    from .ProxyHandler import AutoProxyHandler, GAEProxyHandler
  File "E:\tools\GotoX\GotoX\local\ProxyHandler.py", line 33, in <module>
    from .RangeFetch import RangeFetchs
  File "E:\tools\GotoX\GotoX\local\RangeFetch.py", line 13, in <module>
    from .GAEFetch import get_appid, mark_badappid, gae_urlfetch
  File "E:\tools\GotoX\GotoX\local\GAEFetch.py", line 38, in <module>
    LimitGAE.init()
  File "E:\tools\GotoX\GotoX\local\common\util.py", line 307, in init
    cls._limiter = cls._limiterFactory()
  File "E:\tools\GotoX\GotoX\local\common\util.py", line 302, in _limiterFactory
    return Limiter(cls.maxsize)
  File "E:\tools\GotoX\GotoX\local\common\util.py", line 225, in __init__
    raise ValueError('The maxsize can not be less than 1.')
ValueError: The maxsize can not be less than 1.

**Comment by SeaHOH** [comment]
已修复，请手动更新至主分支。

**Comment by wz7465** [comment]
还有一个问题想反映下，在8087端口下访问国内网站guancha.cn会报错，调用gae模块在8086端口下访问则正常
-----------------------------------------------------------
12:27:55 W L4:10461-> 转发到 'i.guancha.cn' 失败：LimiterFull(-1, (<class 'local.HTTPUtil.LimitConnection'>, '58.220.28.63'))
12:27:56 I L4:10527->[2401:b180:2000:20::27] "FWD CONNECT z4.cnzz.com:443 HTTP/1.1" - -
12:27:57 W [picker gae] 当前 gae IP 数量为 0
12:27:57 I L4:10534->58.220.28.63 "FWD CONNECT i.guancha.cn:443 HTTP/1.1" - -
12:28:02 W L4:10461-> 转发到 'i.guancha.cn' 失败：LimiterFull(-1, (<class 'local.HTTPUtil.LimitConnection'>, '58.220.28.63'))
12:28:08 W L4:10540-> 转发到 'i.guancha.cn' 失败：LimiterFull(-1, (<class 'local.HTTPUtil.LimitConnection'>, '58.220.28.63'))
12:28:14 W L4:10540-> 转发到 'i.guancha.cn' 失败：LimiterFull(-1, (<class 'local.HTTPUtil.LimitConnection'>, '58.220.28.63'))
12:28:16 I L4:10553->58.220.28.63 "FWD CONNECT i.guancha.cn:443 HTTP/1.1" - -

**Comment by SeaHOH** [comment]
@wz7465 
这是因为连接数量超出配置中的限制数量，一般不用管它。如果网站加载不正常，可以把它的域名加入`direct`规则。一般不建议增大限制数量。
下次这种不相关的问题，请新开一帖发问，谢谢合作。

**Comment by wz7465** [comment]
好的
