### ISSUE TITLE
貌似是交叉引用的问题？

### ISSUE THREAD

**Issue by lshilshi** [SeaHOH/GotoX#132]
```
Traceback (most recent call last):
  File "D:\GreenProgram\GotoX\start.py", line 9, in <module>
    from local import proxy
  File "D:\GreenProgram\GotoX\local\proxy.py", line 54, in <module>
    from .GlobalConfig import GC
  File "D:\GreenProgram\GotoX\local\GlobalConfig.py", line 12, in <module>
    from .common.net import isip, isipv6
  File "D:\GreenProgram\GotoX\local\common\net.py", line 13, in <module>
    from local.GlobalConfig import GC
ImportError: cannot import name 'GC'
```
没有git客户端，直接从gh扒拉zip文件更新gotox代码的
就出现这个问题

应该是交叉引用GC类的问题吧

**Comment by SeaHOH** [comment]
这个版本只存在了六分钟，你再更新试试。

**Comment by SeaHOH** [comment]
哦，不对，居然没清理干净。

**Comment by SeaHOH** [comment]
好了，改过来了。
