### ISSUE TITLE
伪造加密连接失败

### ISSUE THREAD

**Issue by hhwhtl** [SeaHOH/GotoX#138]
正常启动最新版的GotoX后，日志提示“伪造加密连接失败”，浏览器显示“您的连接不是私密连接”，已经加入了个人ip，不知道哪里操作不正确了。

**Comment by SeaHOH** [comment]
请提供日志

**Comment by hhwhtl** [comment]
================================================================================
20:44:31 I IP 列表 'google_cn' 解析结果：iplist=['203.208.50.184', '203.208.39.207', '203.208.50.95', '203.208.39.223', '203.208.50.79', '203.208.50.183', '203.208.39.215', '203.208.50.191', '203.208.50.175', '203.208.39.216', '203.208.50.88', '203.208.50.87']
20:44:31 W 检查和导入证书时发生错误：OSError('exception: access violation reading 0x000000001B1E6A40',)
如果没有导入过证书，请手动操作，否则请忽视这条警告。
20:44:31 W 检查和导入证书时发生错误：OSError('exception: access violation reading 0x000000001C25E8E0',)
如果没有导入过证书，请手动操作，否则请忽视这条警告。
20:44:31 W install root certificate failed, Please run as administrator/root/sudo
20:44:42 E L4:14260-> 伪造加密连接失败：host='i.ytimg.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:45 E L4:14271-> 伪造加密连接失败：host='www.youtube.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:45 E L4:14272-> 伪造加密连接失败：host='www.youtube.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:45 E L4:14273-> 伪造加密连接失败：host='fonts.googleapis.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:45 E L4:14274-> 伪造加密连接失败：host='fonts.gstatic.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:45 E L4:14275-> 伪造加密连接失败：host='i.ytimg.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:46 E L4:14281-> 伪造加密连接失败：host='www.youtube.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:50 E L4:14301-> 伪造加密连接失败：host='mail.google.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
20:44:56 E L4:14330-> 伪造加密连接失败：host='clients4.google.com'，Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)
Traceback (most recent call last):
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\ProxyHandler.py", line 1046, in do_FAKECERT
    ssl_sock.do_handshake_server_side()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 85, in do_handshake_server_side
    self.__iowait(self._connection.do_handshake)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\local\compat\openssl.py", line 32, in __iowait
    return io_func(*args, **kwargs)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\hltfywhhw\Desktop\GotoX-3.5.5-cp36-win_amd64_2\python\site-packages\pyOpenSSL-19.0.0-py2.py3-none-any.egg\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]

**Comment by SeaHOH** [comment]
第一次使用请导入证书，否则请删除旧证书重新导入。

**Comment by hhwhtl** [comment]
好的，我试试，谢谢

**Comment by hhwhtl** [comment]
删除证书重新导入没有解决，应该不是这个问题

**Comment by hhwhtl** [comment]
之前正常使用的，看到这两天文件有更新下载了新的，不知道为什么出现这种情况了

**Comment by SeaHOH** [comment]
你的系统、浏览器分别是什么？删除证书重新导入具体是如何操作的？

火狐浏览器删除证书后需要重启浏览器。

**Comment by hhwhtl** [comment]
可以用了，试了试，确实是证书问题，之前是下载了ca.cer安装，后来下载了GotoXCA.crt安装后解决，怪我自己没有仔细阅读readme.md，给老师添麻烦了，再次感谢耐心指导

**Comment by SeaHOH** [comment]
你可真客气，还在叫老师，我不是啊。

**Comment by k79e** [comment]
我也遇到了 这个是有时候有有时候没有 不知道为啥.
我这里错误信息是
![image](https://user-images.githubusercontent.com/6483602/75038447-59488d80-54f1-11ea-9a71-d7edc1152b57.png)

**Comment by SeaHOH** [comment]
服务器 IP 是会变动的，也许当时是 IP 分配到了别人的私人服务。
