### ISSUE TITLE
U2B 报错

### ISSUE THREAD

**Issue by shenyiwd** [SeaHOH/GotoX#152]
Exception happened during processing of request from ('127.0.0.1', 9814)
Traceback (most recent call last):
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyServer.py", line 125, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\socketserver.py", line 360, in finish_request
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyHandler.py", line 129, in __init__
    self.handle()
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\server.py", line 426, in handle
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyHandler.py", line 186, in handle_one_request
    self.do_CONNECT()
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyHandler.py", line 288, in do_CONNECT
    self.do_action()
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "F:\Program Files\XX-Net\GotoX-master\local\ProxyHandler.py", line 1024, in do_PROXY
    proxyport = int(proxyport)
ValueError: invalid literal for int() with base 10: 'follow'
----------------------------------------
就是youtube一直转圈 其他网站打开都还算正常
是因为这个报错吗

**Comment by SeaHOH** [comment]
1. 请求处理进入 `do_PROXY`，说明你为这个报错的 URL 设置了 `proxy` 规则，但没有提供第三方代理地址。`@follow`（你写成 `follow` ）只能用于 `cfw` 规则，如果你只是不小心写错位置，把这条规则放到 `cfw` 规则段中就好。

1. 你使用的版本有少许 bug，虽然现在你并未触发它，但建议更新到主分支。

1. 如果你要观看 youtube 视频，默认规则应该可以，无需自行设置。只是速度不稳定，高峰期带宽会被 CloudFlare 限制到很小。

**Comment by shenyiwd** [comment]
> 1. 请求处理进入 `do_PROXY`，说明你为这个报错的 URL 设置了 `proxy` 规则，但没有提供第三方代理地址。`@follow`（你写成 `follow` ）只能用于 `cfw` 规则，如果你只是不小心写错位置，把这条规则放到 `cfw` 规则段中就好。
> 2. 你使用的版本有少许 bug，虽然现在你并未触发它，但建议更新到主分支。
> 3. 如果你要观看 youtube 视频，默认规则应该可以，无需自行设置。只是速度不稳定，高峰期带宽会被 CloudFlare 限制到很小。

额 我用的就是默认规则啊 我所有设置都没改动的…

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/GotoX/blob/99fcdb0c166eb11e48ebb209eadebd288f24456f/config/ActionFilter.ini#L198
嗯，确实是，不小心注释掉了，把这个分号去掉就行。
