### ISSUE TITLE
运行出错，CPython还是config文件的问题？

### ISSUE THREAD

**Issue by lshilshi** [SeaHOH/GotoX#155]
```
Fatal Python error: ffi.from_handle() detected that the address passed points to
 garbage. If it is really the result of ffi.new_handle(), then the Python object
 has already been garbage collected
Python runtime state: initialized

Thread 0x00000518 (most recent call first):
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\_threading.py", line 60 in wait
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\_threading.py", line 146 in get
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\threadpool.py", line 155 in run

Current thread 0x00001174 (most recent call first):
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\_ffi\loop.py", line 264 in python_stop
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\libuv\loop.py", line 498 in __run_queued_callbacks
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\libuv\loop.py", line 218 in _run_callbacks
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\_ffi\loop.py", line 300 in python_prepare_callback
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\libuv\loop.py", line 542 in run
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win32
.egg\gevent\hub.py", line 618 in run
```

描述，升级后出错，反复测试几次才发现，和config.user文件有关
保持默认没问题，修改了本文件就会出错……
win7 x64 环境

**Comment by SeaHOH** [comment]
看起来像是配置不合适，如果方便的话，上传修改过的 config.user.ini 和 gloop.conf 。

另外，你可以先换 x64 版本试试。

**Comment by lshilshi** [comment]
> 看起来像是配置不合适，如果方便的话，上传修改过的 config.user.ini 和 gloop.conf 。
> 
> 另外，你可以先换 x64 版本试试。

config.user,后面再仔细看了一下，只要自定义了server/localserver/dns的地址就会运行即出错
我后面全部保持默认，只是更新了cfw的服务地址和密码，运行正常，不过只要浏览器一连接，立马出错，还未测试是不是32还是x64的版本缘故
gloop.conf是什么作用？

**Comment by lshilshi** [comment]
> 看起来像是配置不合适，如果方便的话，上传修改过的 config.user.ini 和 gloop.conf 。
> 
> 另外，你可以先换 x64 版本试试。
更换x64版本，全部默认配置
```
17:56:05 I IP 列表 'google_cn' 解析结果：iplist=['203.208.43.98', '203.208.50.16
2', '203.208.50.66', '203.208.50.98']
Fatal Python error: ffi.from_handle() detected that the address passed points to
 garbage. If it is really the result of ffi.new_handle(), then the Python object
 has already been garbage collected
Python runtime state: initialized

Thread 0x00001370 (most recent call first):
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\_threading.py", line 60 in wait
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\_threading.py", line 146 in get
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\threadpool.py", line 155 in run

Current thread 0x000010c8 (most recent call first):
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\_ffi\loop.py", line 264 in python_stop
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\libuv\loop.py", line 498 in __run_queued_callbacks
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\libuv\loop.py", line 218 in _run_callbacks
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\_ffi\loop.py", line 300 in python_prepare_callback
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\libuv\loop.py", line 542 in run
  File "D:\GreenProgram\GotoX\python\site-packages\gevent-20.5.0-cp38-cp38-win_a
md64.egg\gevent\hub.py", line 618 in run
```
其实x32版本运行错误一样，启用运行正常的config也一样错误

**Comment by SeaHOH** [comment]
gloop.conf 是 loop 类型配置文件，估计是这个配置不合适。
看起来你似乎选择了 libuv-cffi，建议换 libev-cext 再次尝试。还有，试试 x64 版本。

**Comment by SeaHOH** [comment]
gloop.conf 是 loop 类型配置文件，估计是这个配置不合适。
看起来你似乎选择了 libuv-cffi，建议换 libev-cext 再次尝试。

**Comment by lshilshi** [comment]
> gloop.conf 是 loop 类型配置文件，估计是这个配置不合适。
> 看起来你似乎选择了 libuv-cffi，建议换 libev-cext 再次尝试。

抱歉，这个有点高深了，就不懂了
直接下的项目release的3.6.0的zip，x64换x32都测试过
现在仅更新了config.user中的cfw地址与对应密码
运行多次都是在解析出google_cn的ip后出错，出错log如上

**Comment by lshilshi** [comment]
> gloop.conf 是 loop 类型配置文件，估计是这个配置不合适。
> 看起来你似乎选择了 libuv-cffi，建议换 libev-cext 再次尝试。

release 文件中附带的是cffi-1.14.0-cp38-cp38-win_amd64.egg，不懂如何切换

**Comment by SeaHOH** [comment]
托盘菜单第一个子菜单，选择 libev-cext 。

**Comment by lshilshi** [comment]
> 托盘菜单第一个子菜单，选择 libev-cext 。

谢谢！才注意到这个菜单，以前因为不清楚什么用处，都是跳过了。

换为libev-cext后，到时预先的google_cn和cdn_wiki这3个的ip能正确刷出来了
但是一连接访问，就会出错，切换为其它几个选项以及no和默认，都一样
以下是错误信息
```
21:49:21 W [picker gws] 当前 gws IP 数量为 0
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52003)
Traceback (most recent call last):
  File "D:\GreenProgram\GotoX\local\ProxyServer.py", line 125, in process_reques
t_thread
    self.finish_request(request, client_address)
  File "socketserver.py", line 360, in finish_request
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 129, in __init__
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 186, in handle_one_re
quest
    self.do_CONNECT()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1484, in do_CONNECT
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1138, in do_FAKECERT
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 188, in handle_one_re
quest
    self.do_METHOD()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1491, in do_METHOD
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 647, in do_CFW
    if self.target and '@follow' in self.target:
AttributeError: 'ACTProxyHandler' object has no attribute 'target'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52010)
Traceback (most recent call last):
  File "D:\GreenProgram\GotoX\local\ProxyServer.py", line 125, in process_reques
t_thread
    self.finish_request(request, client_address)
  File "socketserver.py", line 360, in finish_request
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 129, in __init__
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 186, in handle_one_re
quest
    self.do_CONNECT()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1484, in do_CONNECT
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1138, in do_FAKECERT
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 188, in handle_one_re
quest
    self.do_METHOD()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1491, in do_METHOD
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 647, in do_CFW
    if self.target and '@follow' in self.target:
AttributeError: 'ACTProxyHandler' object has no attribute 'target'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52032)
Traceback (most recent call last):
  File "D:\GreenProgram\GotoX\local\ProxyServer.py", line 125, in process_reques
t_thread
    self.finish_request(request, client_address)
  File "socketserver.py", line 360, in finish_request
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 129, in __init__
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 186, in handle_one_re
quest
    self.do_CONNECT()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1484, in do_CONNECT
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1138, in do_FAKECERT
    self.handle()
  File "http\server.py", line 427, in handle
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 188, in handle_one_re
quest
    self.do_METHOD()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 1491, in do_METHOD
    self.do_action()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 232, in do_action
    getattr(self, self.action)()
  File "D:\GreenProgram\GotoX\local\ProxyHandler.py", line 647, in do_CFW
    if self.target and '@follow' in self.target:
AttributeError: 'ACTProxyHandler' object has no attribute 'target'
----------------------------------------
```

**Comment by SeaHOH** [comment]
更新到主分支，下载覆盖。

**Comment by lshilshi** [comment]
> 更新到主分支，下载覆盖。

ok，在下载master branch的zip覆盖后，现在正常了
thanks！
