### ISSUE TITLE
启动错误 module 'errno' has no attribute 'WSAENAMETOOLONG'

### ISSUE THREAD

**Issue by giveup** [SeaHOH/GotoX#16]
版本是https://github.com/SeaHOH/GotoX/commit/55a23ab1e3d6a28efa58e3b27fecc63eaa67bec9
上一个可以启动的版本似乎是https://github.com/SeaHOH/GotoX/commit/361ed8e4b9b6d3a4f90344f5019793e0e9de1f41
```
Traceback (most recent call last):
  File "/GotoX/start.py", line 13, in <module>
    from local import proxy
  File "/GotoX/local/proxy.py", line 54, in <module>
    from .common import gevent, app_root
  File "/GotoX/local/common/__init__.py", line 51, in <module>
    reset_errno = errno.ECONNRESET, errno.WSAENAMETOOLONG, errno.ENAMETOOLONG
AttributeError: module 'errno' has no attribute 'WSAENAMETOOLONG'
```

**Comment by SeaHOH** [comment]
我知道了，这个是操作系统没有这个，我忘记考虑这个了。
等会而我改成数字就好了。
