### ISSUE TITLE
3.8.0版出现错误

### ISSUE THREAD

**Issue by hg123** [SeaHOH/GotoX#180]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GotoX\start.py", line 25, in <module>
    from local import proxy
  File "C:\Users\Administrator\Desktop\GotoX\local\proxy.py", line 89, in <module>
    from .common.dns import _dns_resolve as dns_resolve, dns_system_servers, dns_remote_servers, dns_local_servers, doh_servers
  File "C:\Users\Administrator\Desktop\GotoX\local\common\dns.py", line 127, in <module>
    servers_2_addresses('1.1.1.1|1.0.0.1'.split('|'))
TypeError: servers_2_addresses() missing 1 required positional argument: 'default_port'

**Comment by miketwes** [comment]
local/common/dns.py line 127,  line 130 后面各加一个53

![2021-03-19_852x471](https://user-images.githubusercontent.com/6849681/111746949-aac87500-88c9-11eb-9e3a-50771c077a26.png)

**Comment by hg123** [comment]
嗯 谢谢 已解决

**Comment by SeaHOH** [comment]
我发觉自己总是能干出这种事情，已发新版。。。
