### ISSUE TITLE
在iphone 上已安装证书,还是提示“ 伪造加密链接失败

### ISSUE THREAD

**Issue by gxggsrmyy** [SeaHOH/GotoX#22]
在iphone 上已安装证书，还是提示“ 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)')”
同样的 xx-net goproxy 也是一样的安装证书，使用没有问题
```

**Comment by SeaHOH** [comment]
没有苹果设备，无法测试。
你先尝试把 `[link/localssl]` 设置成 `TLSv1`，重新启动 GotoX 试一下。如果不行我再想其它办法。

**Comment by gxggsrmyy** [comment]
还是不行，还是一样出错，为什么xx-net 自动生成只有一个ca.crt 证书，而gotox 生成三个 ca.crt ，CAkey.pem，subkey.pem？

**Comment by gxggsrmyy** [comment]
测试gotox 比xx-net 速度快，相比goproxy 没有下载大小限制，希望大海兄@SeaHOH 尽快完善

**Comment by SeaHOH** [comment]
只需要导入 CA.crt  就好。
我上面先写错了，你是用参数 `TLS` 尝试的吗，错误日志是否相同？

**Comment by SeaHOH** [comment]
记得 iphone 导入后还需设置信任，这个操作是做了的吧。

**Comment by gxggsrmyy** [comment]
@SeaHOH 把 [link/localssl] 设置成 TLS，启动出错。

Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from local import proxy
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\proxy.py", line 65, in <module>
    from .GlobalConfig import GC
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\GlobalConfig.py", line 35, in <module>
    class GC:
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\GlobalConfig.py", line 82, in GC
    LINK_LOCALSSL = _SSLv[LINK_LOCALSSLTXT]
KeyError: 'TLS'

**Comment by SeaHOH** [comment]
你是不是直接使用的 release 版本？下载主分支代码覆盖一下，有更新。

**Comment by gxggsrmyy** [comment]
![img_1812](https://cloud.githubusercontent.com/assets/12831337/25171073/315cfc34-251f-11e7-94e0-4b94d0427d10.png)

**Comment by gxggsrmyy** [comment]
iphone 上用自带的浏览器访问，点下载证书就会安装了，xx-net 和goproxy 也是这样安装就可以用了。不需设置信任

**Comment by gxggsrmyy** [comment]
已下载主分支代码覆盖， 还是一样的出错

**Comment by SeaHOH** [comment]
好吧，我没用过。
新设置怎么样，有用没？

**Comment by gxggsrmyy** [comment]
已下载主分支代码覆盖， 还是一样的出错

**Comment by gxggsrmyy** [comment]
设置成 SSLv23 也不行

**Comment by SeaHOH** [comment]
麻烦你试一下这个修改 https://github.com/SeaHOH/GotoX/commit/0976f781df4d088a61f953d21087f0511a7fd99a，不行我再改。

**Comment by gxggsrmyy** [comment]
修改 0976f78还是不行

20:48:17 E 192.168.31.173:50461-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)

**Comment by gxggsrmyy** [comment]
21:12:21 E 192.168.31.125:64108-> 伪造加密链接失败：host='i.ytimg.com'，SSLError(1, '[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:720)

**Comment by gxggsrmyy** [comment]
21:21:24 E 192.168.31.125:64205-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)

21:21:24 E 192.168.31.125:64207-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)

21:21:24 E 192.168.31.125:64208-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)

21:21:24 E 192.168.31.125:64210-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)

**Comment by SeaHOH** [comment]
这个修改呢 https://github.com/SeaHOH/GotoX/commit/748c779087c1e88987ad33993c820f16253d5f8d ，麻烦你再次测试。

**Comment by gxggsrmyy** [comment]
出错, 已经删除 cert/certs 子文件夹
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58483)
Traceback (most recent call last):
  File "socketserver.py", line 625, in process_request_thread
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyServer.py", line 106, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "socketserver.py", line 681, in __init__
  File "http\server.py", line 422, in handle
  File "http\server.py", line 410, in handle_one_request
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 1059, in do_CONNECT
    self.do_action()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 122, in do_action
    getattr(self, self.action)()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 759, in do_FAKECERT
    context = self.get_context()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 1000, in get_context
    certfile, keyfile = CertUtil.get_cert(host, ip)
NameError: name 'ip' is not defined
----------------------------------------

**Comment by SeaHOH** [comment]
不好意思，忘了定义变量。
这回加上了 https://github.com/SeaHOH/GotoX/commit/fa3506afb1b76a929c195a1f3d34540d76a66c60

**Comment by gxggsrmyy** [comment]
还是出错，，
23:00:32 E 192.168.31.125:64246-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:720)

23:00:32 E 192.168.31.125:64247-> 伪造加密链接失败：host='m.youtube.com'，SSLError(1, '[SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:720)

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/GotoX/commit/4e2fcd5b077cb27e9a21162b64c5b43f7b1a6780 这是能想到最后的地方了，需要将 CAkey.pem 文件删除，然后重新运行并导入新的证书。

**Comment by gxggsrmyy** [comment]
还是不行

00:06:49 E 192.168.31.125:65193-> 伪造加密链接失败：host='i.ytimg.com'，SSLError(1, '[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:720)')
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 761, in do_FAKECERT
    ssl_sock = context.wrap_socket(self.connection, server_side=True)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 58, in wrap_socket
    _session=session)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 229, in __init__
    raise x
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 225, in __init__
    self.do_handshake()
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\python\site-packages\gevent-1.2.1-cp35-win32.egg\gevent\_ssl3.py", line 549, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:720)

**Comment by SeaHOH** [comment]
其实我很纳闷 `UNKNOWN_CA` 这个错误的，照理安装好了证书是不会有这个错误的，即使证书认证时可能出错。
暂时我没法处理这个问题了，感谢你陪我折腾这么多时间。 :smiley:

**Comment by gxggsrmyy** [comment]
为什么要搞多个证书，象xx-net 只有一个证书不好吗,只有一个ca.crt

**Comment by gxggsrmyy** [comment]
相比xx-net ，是不是多了一级加密

#本地加密 SSLv23, SSLv3, TLSv1, TLSv1.1, TLSv1.2，默认 SSLv23
localssl = 
#远程加密 TLSv1, TLSv1.1, TLSv1.2，默认 TLSv1.2
remotessl =

**Comment by gxggsrmyy** [comment]
@SeaHOH 你找一个ios 设备来试，说不定一下就发现问题了

**Comment by SeaHOH** [comment]
并没有双重加密，`localssl` 是浏览器到本地代理，`remotessl` 是本地代理到远程服务器。
也没有多个证书，CA.crt 是根证书，CAkey.pem 是根证书和密钥，subkey.pem 是子证书密钥。

不好借别人的设备来搞，能借的好像没人用苹果。

**Comment by gxggsrmyy** [comment]
@SeaHOH   gotox 在下载速度方面真的很具优势，速度比xx-net快，相比goproxy 没有下载大小限制，希望继续改进。

**Comment by gxggsrmyy** [comment]
@SeaHOH  不好意思 ，问题找到了，iOS 10.3.1 安装证书以后还需要到 “设置”>“通用”>“关于本机”>"证书信任设置" 打开信任。
用iphone 自带的浏览器能打开youtube ,但不能播放，用 youtube app 播放。
11:50:02 I 发现[autorange]匹配：'https://r19---sn-vgqsen7s.googlevideo.com/videoplayback?requiressl=yes&ip=107.178.194.84&gir=yes&mime=video%2Fmp4&key=cms1&expire=1492681735&clen=395229278&ratebypass=yes&lmt=1491083771263101&dur=5897.984&ipbits=0&pl=28&ei=py_4WP9ElM65ArP9l-AB&source=youtube&id=o-AHJ3Xlg2UuWs3KiC8PjCn3t7pVYMdTQqeiDzdhOXeKfi&itag=18&upn=M7zxiw5n3eQ&signature=69A36EC6CDC6A64A9382E3327C0BEAD187EAE508.022DEC3B5FB1F346B3144FA24C0900F4B7DCD242&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&cpn=OQ5xaLg37HLPVxe0&c=MWEB&cver=1.20170412&ptk=iu3WYyQ-5QcZPtkZJwalPQ&oid=ikTalHYqqSmMe08vabKNRQ&ptchn=iu3WYyQ-5QcZPtkZJwalPQ&pltype=content&redirect_counter=1&req_id=9556c4e491efc63&cms_redirect=yes&ipbypass=yes&mm=26&mn=sn-vgqsen7s&ms=onr&mt=1492660093&mv=m'
11:50:02 W 74.125.170.218 do_GAE "GET https://r19---sn-vgqsen7s.googlevideo.com/videoplayback?requiressl=yes&ip=107.178.194.84&gir=yes&mime=video%2Fmp4&key=cms1&expire=1492681735&clen=395229278&ratebypass=yes&lmt=1491083771263101&dur=5897.984&ipbits=0&pl=28&ei=py_4WP9ElM65ArP9l-AB&source=youtube&id=o-AHJ3Xlg2UuWs3KiC8PjCn3t7pVYMdTQqeiDzdhOXeKfi&itag=18&upn=M7zxiw5n3eQ&signature=69A36EC6CDC6A64A9382E3327C0BEAD187EAE508.022DEC3B5FB1F346B3144FA24C0900F4B7DCD242&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&cpn=OQ5xaLg37HLPVxe0&c=MWEB&cver=1.20170412&ptk=iu3WYyQ-5QcZPtkZJwalPQ&oid=ikTalHYqqSmMe08vabKNRQ&ptchn=iu3WYyQ-5QcZPtkZJwalPQ&pltype=content&redirect_counter=1&req_id=9556c4e491efc63&cms_redirect=yes&ipbypass=yes&mm=26&mn=sn-vgqsen7s&ms=onr&mt=1492660093&mv=m" 返回：AttributeError("'GAEProxyHandler' object has no attribute 'range_end'",)，重试
11:50:03 E 173.194.57.135 do_GAE "GET https://r19---sn-vgqsen7s.googlevideo.com/videoplayback?requiressl=yes&ip=107.178.194.84&gir=yes&mime=video%2Fmp4&key=cms1&expire=1492681735&clen=395229278&ratebypass=yes&lmt=1491083771263101&dur=5897.984&ipbits=0&pl=28&ei=py_4WP9ElM65ArP9l-AB&source=youtube&id=o-AHJ3Xlg2UuWs3KiC8PjCn3t7pVYMdTQqeiDzdhOXeKfi&itag=18&upn=M7zxiw5n3eQ&signature=69A36EC6CDC6A64A9382E3327C0BEAD187EAE508.022DEC3B5FB1F346B3144FA24C0900F4B7DCD242&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&cpn=OQ5xaLg37HLPVxe0&c=MWEB&cver=1.20170412&ptk=iu3WYyQ-5QcZPtkZJwalPQ&oid=ikTalHYqqSmMe08vabKNRQ&ptchn=iu3WYyQ-5QcZPtkZJwalPQ&pltype=content&redirect_counter=1&req_id=9556c4e491efc63&cms_redirect=yes&ipbypass=yes&mm=26&mn=sn-vgqsen7s&ms=onr&mt=1492660093&mv=m" 失败：AttributeError("'GAEProxyHandler' object has no attribute 'range_end'",)
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\ProxyHandler.py", line 541, in do_GAE
    rangefetch = RangeFetch(self, url, request_headers, payload, response)
  File "E:\Dropbox\GotoX\GotoX-3.3.5-cp35-win32\local\RangeFetch.py", line 51, in __init__
    self.range_end = handler.range_end
AttributeError: 'GAEProxyHandler' object has no attribute 'range_end'

**Comment by gxggsrmyy** [comment]
xx-net  goproxy 的证书是升级iOS 10.3.1之前安装的，自动打开信任了，害你折腾了这么久。

**Comment by SeaHOH** [comment]
没事，谁都有疏忽的时候嘛。

**Comment by jzp820927** [comment]
ip 暴露了，大胸弟。
.googlevideo.com Url 会显示你的 IP。

**Comment by SeaHOH** [comment]
@卡卡西 :laughing:

**Comment by SeaHOH** [comment]
已经修复，马上上传。

**Comment by jzp820927** [comment]
移动端就是麻烦。

**Comment by gxggsrmyy** [comment]
@SeaHOH  ok,亲测可用，完美了！

**Comment by SeaHOH** [comment]
@jzp820927 
开玩笑哈，干嘛删掉。

**Comment by SeaHOH** [comment]
@gxggsrmyy 
谢谢支持，以后发现错误一定要继续发 issues。

**Comment by jzp820927** [comment]
@SeaHOH 我删掉是因为我发现我发的 issues 说的有错误，就删了。和你没关系。不知道你说的开玩笑是指的什么？

**Comment by SeaHOH** [comment]
@jzp820927 
没错，我是看到你的提醒后才把 IP 删除的。

Copy Ninja 卡卡西啊，难道不知道？

**Comment by jzp820927** [comment]
开始没注意，后来才发现走了 GAE，日志里面的 IP 就变成 GAE 的出口 IP 了，所以不存在泄漏， 然后我就把回复删了。难道是你把 IP 改成 GAE 的 IP 的？

**Comment by SeaHOH** [comment]
走 GAE ，重定向之前的 Url 会记录你的公网 IP，然后才会变成出口 IP。
至于卡卡西嘛，是个动漫人物。

**Comment by jzp820927** [comment]
我之前看都是 GAE 的出口 IP，不是国内的公网 IP，可能是我没注意吧。
