### ISSUE TITLE
NameError: name 'pkgdll_get_path' is not defined，这个如何处理

### ISSUE THREAD

**Issue by yuyeyubee** [SeaHOH/GotoX#230]
win10，py3.9，pycharm运行时遇到这个，请问如何处理：
C:\Python39\python.exe C:/Users/PVer/Downloads/GotoX-3.8.8-cp310-win_amd64/start.py
Traceback (most recent call last):
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\start.py", line 25, in <module>
    from local import proxy
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\local\proxy.py", line 52, in <module>
    compat.init()
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\local\common\decorator.py", line 16, in newfunc
    result = func(*args, **kwargs)
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\local\compat\__init__.py", line 118, in init
    import gevent
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\__init__.py", line 85, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\_config.py", line 699, in <module>
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\_config.py", line 146, in get
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\_config.py", line 248, in validate
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\_config.py", line 219, in _import_one_of
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\_config.py", line 237, in _import_one
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\libev\corecext.py", line 8, in <module>
  File "C:\Users\PVer\Downloads\GotoX-3.8.8-cp310-win_amd64\python\site-packages\gevent-21.12.0-cp310-cp310-win_amd64.egg\gevent\libev\corecext.py", line 4, in __bootstrap__
NameError: name 'pkgdll_get_path' is not defined

**Comment by SeaHOH** [comment]
使用其它已安装的 Python 请下载 zip 打包的版本，并自行安装依赖。否则，请直接从 start.vbs 启动。
