### ISSUE TITLE
404 无法找到给定的网址

### ISSUE THREAD

**Issue by wzwtt** [SeaHOH/GotoX#238]
使用CFW方式，配置后访问Twitter、Facebook等均正常，但访问谷歌系列网站如android.com，google.com，youtube.com等网站时浏览器内均显示** 404 无法找到给定的网址 ** ，debug内容如下：
<img width="755" alt="sshot-1" src="https://user-images.githubusercontent.com/21050445/188257205-ef8c70b2-3950-4aca-920f-5bd931e190b4.png">
且gws地址筛选异常缓慢，4小时仍然才完成千余个地址的筛选。

**Comment by SeaHOH** [comment]
其实今天我也没有成功直连，如果你是今天初次使用，那真是遇到了一个不好的时机，已经很久没有这种长时间无法连接的情况。

至于筛选缓慢的问题，可以通过调整配置来增加筛选线程。

**Comment by gxggsrmyy** [comment]
@SeaHOH 我发现一个问题不知当讲不当讲, openwrt 平台, 因为没有可以安装的gevent , 以往我都是设置(gloop.nogevent: 1) 才能正常使用, 而最近更新程序后发现,, 即使设置(gloop.nogevent: 1)  ,依然提示 gevent 方面的报错, 只有把python\site-packages目录下的gevent-21.12.0-cp310-cp310-win_amd64.egg 删除 ,才不会报错, 而之前只要设置(gloop.nogevent: 1) 就行了.

**Comment by SeaHOH** [comment]
> @SeaHOH 我发现一个问题不知当讲不当讲, openwrt 平台, 因为没有可以安装的gevent , 以往我都是设置(gloop.nogevent: 1) 才能正常使用, 而最近更新程序后发现,, 即使设置(gloop.nogevent: 1) ,依然提示 gevent 方面的报错, 只有把python\site-packages目录下的gevent-21.12.0-cp310-cp310-win_amd64.egg 删除 ,才不会报错, 而之前只要设置(gloop.nogevent: 1) 就行了.

@gxggsrmyy 我记得你之前就问过类似的问题，Windows 便携打包无法在其它系统中正常工作，请下载纯脚本并另行安装依赖。

**Comment by SeaHOH** [comment]
@gxggsrmyy 昨天回复时没有注意到你真正的问题，你只需要根据提示“使用 nogevent **参数**重新启动”，而不是设置 `gloop.nogevent: 1`。

**Comment by gxggsrmyy** [comment]
config\gloop.conf 文件的内容如下:
gloop.libev-cext: 0
gloop.libev-cffi: 0
gloop.libuv-cffi: 0
gloop.nogevent: 1
难道不是“使用 nogevent 参数重新启动”吗?  @SeaHOH

**Comment by gxggsrmyy** [comment]
刚发现比以前多了一个 config\win_tray.conf 文件,里面的内容:
wintray.gloop.libev-cext: 0
wintray.gloop.libev-cffi: 0
wintray.gloop.libuv-cffi: 0
wintray.gloop.nogevent: 1
难道 gloop.conf和 win_tray.conf 都要设置?

**Comment by SeaHOH** [comment]
@gxggsrmyy 
你的方法是修改配置，启动参数是这样的：

    start.py nogevent

或者单独新建个启动文件 `start`，内容为：

    #!/bin/sh
    start.py nogevent

首次运行前设置权限：

    chmod +x start

**Comment by gxggsrmyy** [comment]
@SeaHOH 不好意思, 无论是修改配置，还是加启动参数, 如果不把gevent-21.12.0-cp310-cp310-win_amd64.egg 删除, 依然会出错.
root@OpenWrt 07:13 PM ~# python3    /mnt/sda/GotoX-master/start.py nogevent
Traceback (most recent call last):
File "/mnt/sda/GotoX-master/start.py", line 25, in <module>
from local import proxy
File "/mnt/sda/GotoX-master/local/proxy.py", line 64, in <module>
from gevent import __version__ as geventver
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/__init__.py", line 85, in <module>
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/_config.py", line 699, in <module>
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/_config.py", line 146, in get
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/_config.py", line 248, in validate
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/_config.py", line 219, in _import_one_of
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/_config.py", line 237, in _import_one
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/libev/corecext.py", line 8, in <module>
File "/mnt/sda/GotoX-master/python/site-packages/gevent-21.12.0-cp39-cp39-win_amd64.egg
/gevent/libev/corecext.py", line 4, in __bootstrap__
NameError: name 'pkgdll_get_path' is not defined

**Comment by SeaHOH** [comment]
> @SeaHOH 不好意思, 无论是修改配置，还是加启动参数, 如果不把gevent-21.12.0-cp310-cp310-win_amd64.egg 删除, 依然会出错.

我↓↓↓这段回复↓↓↓也不是白写的啊，有具体指出你使用中的不当之处，你提到的文件本就不该出现才对。

> 我记得你之前就问过类似的问题，**Windows 便携打包无法在其它系统中正常工作**，请下载纯脚本并另行安装依赖。

你**必须先修正问题** (移除并重新按正确的步骤安装)，然后才能应用正确的解决方案 (以应对无预编译 C 扩展的包)，即使用适合的参数启动，或者自己编译其实也是可以的 (当然你并不需要这个，因此之前根本就没提它)。

**Comment by SeaHOH** [comment]
> 不知道我表达清楚了吗, 我的意思是 在我之前的使用过程中, 并没有把gevent-21.12.0-cp310-cp310-win_amd64.egg 删除, 只是通过配置不使用gevent , 就可以正常运行了, 而现在必须把 gevent-21.12.0-cp310-cp310-win_amd64.egg 删除, 我不知道纠结这些细节有没有意义, 只是想从技术上探讨 python 的问题. 我想大概是 os.path.join(dirname, 'python') 方面的问题, 但我的水平低又有技术洁癖，搞好了可以解决不同平台使用的通用性问题, 茴香豆的几种写法不知有没有意义 . @SeaHOH

嘿，你早说啊。不过，就我目前认识水平理解，当前已是最具可行性之发行方案。
如果你还有一些别出心裁的想法，也是不错的。这样，你先找一个 Python 编程入门教程，大略翻看学习一遍基础概念；然后在网上搜索一些着重 Python 包发行打包及其 C 扩展的文章，读一读，汲取相关领域的前人经验；最后再来这里谈下你的想法，并讨论改进方案的可行性。

**Comment by SeaHOH** [comment]
即使之前确如你所描述那样运作无碍，但这并非刻意设计，除了已声明过的功能可保证大体正常运行，其它都是意外，不确定。
你提到的通用性改进方案不是没有，只是代价收益失衡，没有必要。你想想，普通路由器空间能有多少，如果每安装个软件都要附带一大堆用不着的文件，怎么想都不合适吧。当然，路由器确实是个特例，但就算是其它系统，只要是稍微有点软件基础知识的用户，都不太会喜欢这样，除非储存价格比白菜还不如。那种单个安装搞定一切的，只有发行才会真正喜欢，省事。

另，以后有啥可单开个问题或讨论，不要再像这样乱入主题无关的地方。
