### ISSUE TITLE
新版无法启动

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#266]
运行3.9.1后出现

thread panicked while processing panic. aborting.

**Comment by SeaHOH** [comment]
请提供更多信息。

- 操作系统版本

- Python 版本

- Python 已安装包的版本 (发布页的打包版本不用列出)

- gevent 事件循环配置 (未自行配置则不用列出)

- GotoX 改动过的主配置 (其中 CloudFlare Workers 不用列出)

- 可否稳定复现及其操作步骤

**Comment by gxggsrmyy** [comment]
@SeaHOH  下载的是 GotoX-3.9.1-cp311-win_amd64 版本, 运行GotoX.vbs 就会出现上面的错误. 这么明显的出错, 居然没有发现

**Comment by loveinlastnight** [comment]
是的，就是打包页的版本。WIN11系统。最新源码覆盖后一样的thread panicked while processing panic. aborting.错误。

**Comment by SeaHOH** [comment]
下载打包好的 win_amd64 版本，在 Win11 下通过 GotoX.vbs 运行就能稳定复现，是这样吗？
有可能和更换打包方式有关，虽然我自己已经使用了几个月，但是并未测试 Win7 以外的系统。
这里发两个打包，请帮忙都测试一遍。
[GotoX-3.9.1-cp311-win_amd64_op.7z.zip](https://github.com/SeaHOH/GotoX/files/11663544/GotoX-3.9.1-cp311-win_amd64_op.7z.zip)
[GotoX-3.9.1-cp311-win_amd64_np.7z.zip](https://github.com/SeaHOH/GotoX/files/11663565/GotoX-3.9.1-cp311-win_amd64_np.7z.zip)

@gxggsrmyy 仍然兼容旧版本 cryptography，但不包括最近的 `40.0.0` 和 `40.0.1`，requirements.txt 有描述。
如果你的 cryptography 版本符合要求，但仍然报错，请提供具体信息。

**Comment by gxggsrmyy** [comment]
@SeaHOH 这两个打包都正常

**Comment by SeaHOH** [comment]
看来只是 rust 有兼容性问题，新的打包还可以用，就是需要添加例外处理。

如果可能的话，也请帮忙测试下 Win10。谢谢啦~

**Comment by loveinlastnight** [comment]
@SeaHOH 

WIN11，两个我也都测了，没有问题。
WIN10的话，前几天我测过，发布页的一样错误。这两个新的暂时没有WIN10系统，过两天给你测下。

**Comment by gxggsrmyy** [comment]
@SeaHOH 
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad35600>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7fc9fad36410>>
Traceback (most recent call last):
  File "/root/GotoX/local/HTTPUtil.py", line 731, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, cache_key, server_name)
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
  File "/root/GotoX/local/HTTPUtil.py", line 469, in get_ssl_socket
    context = self.get_context(cache_key)
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
  File "/root/GotoX/local/common/decorator.py", line 66, in newfunc
    return func(*args, **kwargs)
  File "/root/GotoX/local/HTTPUtil.py", line 360, in get_context
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'
    ssl_options |= SSL.OP_IGNORE_UNEXPECTED_EOF
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_IGNORE_UNEXPECTED_EOF'

**Comment by gxggsrmyy** [comment]
@SeaHOH  仔细对比了, 就是 [HTTPUtil.py] 文件更改后出错的

**Comment by SeaHOH** [comment]
@gxggsrmyy 确实是有问题，没考虑周全。

**Comment by SeaHOH** [comment]
@gxggsrmyy 谢谢反馈。
这里确实没有考虑到，会有下载 Windows 打包后，不使用 `vbs`，而是直接运行 `start.py` 的情况。
因为打包自带依赖优先级比本地安装的低，GotoX 支持加载本地的更新依赖。你可以通过安装依赖解决此问题。

之后会修改，当检测到此种情况时，仅加载托盘和通用平台依赖，忽略其它仅 Windows 的 `egg` 文件，并修改适配未安装提示。
