### ISSUE TITLE
启动出错：OSError: [Errno 65] No route to host

### ISSUE THREAD

**Issue by giveup** [SeaHOH/GotoX#30]
```
GotoX  版 本 : 3.3.6 (python/3.6.1 gevent/1.2.1 pyOpenSSL/16.2.0)
 GAE 远程验证 : 已启用

  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086

  代 理 认 证 : 无需认证

  调 试 信 息 : INFO

  链 接 模 式 : 远程 - TLSv1.2 / gevent + OpenSSL
                本地 - TLS / gevent

  网 络 配 置 : ipv4

  IP 数 据 库 : CN IP from APNIC-20170416/20170415 and 17mon-20170401, range count: 3566

  安 装 证 书 : 设置代理后访问 http://gotox.go/
==================================================================================
Traceback (most recent call last):
  File "./start.py", line 14, in <module>
    proxy.main()
  File "/GotoX/local/proxy.py", line 264, in main
    pre_start()
  File "/GotoX/local/proxy.py", line 150, in pre_start
    network_test(True)
  File "/GotoX/local/ProxyServer.py", line 42, in network_test
    get_localhosts()
  File "/GotoX/local/ProxyServer.py", line 69, in get_localhosts
    AutoProxyHandler.localhosts = tuple(set(_localhosts + localhosts + get_listen_ip()))
  File "/GotoX/local/common/proxy.py", line 26, in get_listen_ip
    sock.connect(('2001:4860:4860::8888', 53))
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 308, in connect
    raise error(result, strerror(result))
OSError: [Errno 65] No route to host
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
……
```
版本是https://github.com/SeaHOH/GotoX/commit/7a065d92b374b056d17b38d08f3d371e7651b221

**Comment by SeaHOH** [comment]
谢谢反馈。
忘记检查错误了，已修复。

**Comment by SeaHOH** [comment]
又忘记导入了……
