### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by MyYellowBlanket** [SeaHOH/GotoX#39]
```
IP 测试守护线程错误：IndexError('list index out of range',)
Traceback (most recent call last):
  File "E:\GotoX\local\GAEUpdate.py", line 245, in testipserver
    testonegaeip()
  File "E:\GotoX\local\GAEUpdate.py", line 174, in testonegaeip
    ip = GC.IPLIST_MAP['google_gws'][-1]
IndexError: list index out of range
```
怀疑是-1导致的

**Comment by SeaHOH** [comment]
你的判断是对的，我没考虑到这种情况，估计你的网络受干扰特别严重吧。

**Comment by MyYellowBlanket** [comment]
可能是的. 不过我刚才看了Python的文档, if i is negative, the index is relative to the end of sequence s. 所以Python还有这种操作, -1也是可以的

**Comment by SeaHOH** [comment]
`-1` 本身没问题，但是序列为空时任何值都会报错。
