### ISSUE TITLE
运行报错的问题：OpenSSL.crypto.Error

### ISSUE THREAD

**Issue by hcym** [SeaHOH/GotoX#4]
运行报错的问题！

太长了，重开一贴
>    GotoX 版 本 : 3.3.1 (python/2.7.12+ gevent/1.1.1 pyopenssl/16.2.0)
    GAE APPID :
    GAE 远程验证 : 已启用
    监 听 地 址 : 自动代理 - 127.0.0.1:8087
               GAE 代理 - 127.0.0.1:8086
    链 接 模 式 : 远程 - TLSv1.2/openssl
               本地 - SSLv23/gevent
    链接 配置集 : ipv4
    安 装 证 书 : http://gotox.net/ca
    下 载 证 书 : http://gotox.net/ca 加任意字符
    ==================================================================================
    Traceback (most recent call last):
    File "start.py", line 14, in
    proxy.main()
    File "/home/oem/wallproxy/GotoX-master/local/proxy.py", line 257, in main
    CertUtil.check_ca()
    File "/home/oem/wallproxy/GotoX-master/local/CertUtil.py", line 261, in check_ca
    sub_key = crypto.load_publickey(crypto.FILETYPE_PEM, content)
    File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2547, in load_publickey
    _raise_current_error()
    File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
    OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

subkey.pem
Private RSA Key
Strength: 2048 bits

subkey.pem有内容，大小2.1kib

老的GoAgent-3.0.4，GoAgent-3.0.8就没问题，xx－mini可以

但是XX－net也是不行 

以后再说吧，可能是对环境识别问题

**Comment by SeaHOH** [comment]
还是看出没问题 :persevere: 
我去看看 XX-Net

**Comment by jzp820927** [comment]
确实灵异，我的和他一个系统，一样的环境，我都能运行
