### ISSUE TITLE
Mac启动出错

### ISSUE THREAD

**Issue by giveup** [SeaHOH/GotoX#45]
日志
`Traceback (most recent call last):
  File "./start.py", line 14, in <module>
    proxy.main()
  File "/Users/user/Documents/GotoX/local/proxy.py", line 266, in main
    start_proxyserver()
  File "/Users/user/Documents/GotoX/local/ProxyServer.py", line 204, in start_proxyserver
    AutoProxy.bind_and_activate()
  File "/Users/user/Documents/GotoX/local/ProxyServer.py", line 256, in bind_and_activate
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 0)
OSError: [Errno 22] Invalid argument`

版本是https://github.com/SeaHOH/GotoX/commit/00ac86713e44d1d1b55e283c65c64836e9cceb00
环境信息：
GotoX  版 本 : 3.4.0 (python/3.6.2 gevent/1.2.1 pyOpenSSL/16.2.0)
服务器端：https://github.com/SeaHOH/GotoX/commit/c291176c94186bef97a2774f19a5b689cf2bed77

**Comment by SeaHOH** [comment]
谢谢反馈。
暂时不清楚是那个不支持，那就先关闭这个特性。
