### ISSUE TITLE
OpenWRT LEDE 安装debian后运行GotoX报错

### ISSUE THREAD

**Issue by jlzsss** [SeaHOH/GotoX#76]
报错信息如下：
root@Openwrt:/home/GotoX# python3 start.py
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "/home/GotoX/local/proxy.py", line 257, in main
    sys.stdout.write(''.join(info))
UnicodeEncodeError: 'ascii' codec can't encode character '\u7248' in position 91: ordinal not in range(128)

**Comment by SeaHOH** [comment]
因为有中文，需要系统支持。

不然只能注释掉这句，并增加一句 `logging.disable(50)`。

**Comment by jlzsss** [comment]
修改后，运行python3 start.py无反应
BusyBox v1.28.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 Openwrt Koolshare mod V2.17, r7469-92b40b1 by fw867
 -----------------------------------------------------
root@Openwrt:~# debian
root@Openwrt:/# cd /home/GotoX
root@Openwrt:/home/GotoX# ls
GotoX.ico  README.md  cert  config  data  launcher  local  python  requirements.txt  start.py  web
root@Openwrt:/home/GotoX# python3 start.py

**Comment by jlzsss** [comment]
debian安装设置为zh_CN后，问题解决。

**Comment by SeaHOH** [comment]
谢谢你，提供这些信息。
