### ISSUE TITLE
debian上运行GotoX报错

### ISSUE THREAD

**Issue by jlzsss** [SeaHOH/GotoX#82]
报错信息如下：
Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.186'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8d48: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.186', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.184'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8348: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.184', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.116'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8b48: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.116', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.180'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8c48: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.180', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.115'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8548: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.115', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.118'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8a48: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.118', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.187'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8948: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.187', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.114'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac4d8848: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.114', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.181'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac73a048: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.181', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.185'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac73a148: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.185', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

Traceback (most recent call last):
  File "/home/GotoX/local/HTTPUtil.py", line 401, in _create_ssl_connection
    if cache_key == 'google_fe:443' or host.endswith('.appspot.com'):
AttributeError: 'NoneType' object has no attribute 'endswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/GotoX/local/HTTPUtil.py", line 449, in _create_ssl_connection
    set_connect_finish(ip)
  File "/home/GotoX/local/HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "/home/GotoX/local/common/__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '67.214.191.178'
2018-06-09T01:19:32Z <Greenlet "Greenlet-0" at 0x7f53ac73a248: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x7f53ac66b080>>(('67.214.191.178', 443), 'google_gws:443', None, <queue.Queue object at0x7f53ac4cee10>, 1.72)> failed with KeyError

**Comment by SeaHOH** [comment]
不好意思，很久没用自动扫描功能了，没有注意到。
已发布 3.4.4 的修复版本。

**Comment by jlzsss** [comment]
你好，我用最新版还是报错，报错信息如下：
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'checksysca'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GotoX/start.py", line 13, in <module>
    from local import proxy
  File "/home/GotoX/local/proxy.py", line 50, in <module>
    from .common import gevent, app_root
  File "/home/GotoX/local/common/__init__.py", line 318, in <module>
    from local.GlobalConfig import GC
  File "/home/GotoX/local/GlobalConfig.py", line 37, in <module>
    class GC:
  File "/home/GotoX/local/GlobalConfig.py", line 61, in GC
    LISTEN_CHECKSYSCA = CONFIG.getboolean('listen', 'checksysca')
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'checksysca' in section: 'listen'
root@Openwrt:/# export LC_ALL=zh_CN.UTF-8
root@Openwrt:/# /usr/bin/python3 /home/GotoX/start.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'checksysca'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GotoX/start.py", line 13, in <module>
    from local import proxy
  File "/home/GotoX/local/proxy.py", line 50, in <module>
    from .common import gevent, app_root
  File "/home/GotoX/local/common/__init__.py", line 318, in <module>
    from local.GlobalConfig import GC
  File "/home/GotoX/local/GlobalConfig.py", line 37, in <module>
    class GC:
  File "/home/GotoX/local/GlobalConfig.py", line 61, in GC
    LISTEN_CHECKSYSCA = CONFIG.getboolean('listen', 'checksysca')
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'checksysca' in section: 'listen'
