### ISSUE TITLE
升级3.4.4后发生导入证书错误，手动导入依然无效

### ISSUE THREAD

**Issue by tcwilliy** [SeaHOH/GotoX#84]
18:42:44 W 证书导入失败：OSError('exception: access violation reading 0xFFFFFFFF8EAAF4E0',)
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.1\start.py", line 14, in <module>
    proxy.main()
  File "F:\Free\GOA\GotoX-3.4.1\local\proxy.py", line 263, in main
    CertUtil.check_ca()
  File "F:\Free\GOA\GotoX-3.4.1\local\CertUtil.py", line 284, in check_ca
    if GC.LISTEN_CHECKSYSCA and import_ca() != 0:
  File "F:\Free\GOA\GotoX-3.4.1\local\CertUtil.py", line 212, in import_ca
    if pCertCtx:
UnboundLocalError: local variable 'pCertCtx' referenced before assignment

**Comment by SeaHOH** [comment]
试试这个修改。
顺便问一句，你使用的是否是管理员账户？

**Comment by tcwilliy** [comment]
修改哪个？ 我不是用管理员账户，用的是具有管理员权限账户

**Comment by tcwilliy** [comment]
修改哪个？ 我不是用管理员账户，用的是具有管理员权限账户

**Comment by tcwilliy** [comment]
21:58:13 E CAkey.pem 不存在，清空 certs 文件夹。
21:58:13 W CAkey.pem 不存在，将从系统证书中删除无效的 CA 证书
21:58:13 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000053E6E3C0',)
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\start.py", line 14, in <module>
    proxy.main()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\proxy.py", line 263, in main
    CertUtil.check_ca()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 285, in check_ca
    if GC.LISTEN_CHECKSYSCA and import_ca() != 0:
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 216, in import_ca
    crypt32.CertCloseStore(store_handle, 0)
OSError: exception: access violation writing 0x0000000053E6E370

**Comment by tcwilliy** [comment]
按照你的建议修改后 依然存在这个错误
21:59:06 W 导入证书时发生错误：OSError('exception: access violation reading 0x000000000A967600',)
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\start.py", line 14, in <module>
    proxy.main()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\proxy.py", line 263, in main
    CertUtil.check_ca()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 285, in check_ca
    if GC.LISTEN_CHECKSYSCA and import_ca() != 0:
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 216, in import_ca
    crypt32.CertCloseStore(store_handle, 0)
OSError: exception: access violation writing 0x000000000A9675B0

**Comment by SeaHOH** [comment]
这回大概能运行了，但是可能无法导入证书。

**Comment by tcwilliy** [comment]
问题依旧，放弃治疗，退回3.4.3

**Comment by tcwilliy** [comment]
导入证书时发生错误：OSError('exception: access violation reading 0xFFFFFFFF844C79E0',)
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\start.py", line 14, in <module>
    proxy.main()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\proxy.py", line 263, in main
    CertUtil.check_ca()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 287, in check_ca
    if GC.LISTEN_CHECKSYSCA and import_ca() != 0:
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\CertUtil.py", line 217, in import_ca
    crypt32.CertCloseStore(store_handle, 0)
OSError: exception: access violation writing 0xFFFFFFFF844C7990

**Comment by tcwilliy** [comment]
问题依旧，放弃治疗，退回3.4.3

**Comment by SeaHOH** [comment]
你可以把参数`checksysca`设置为 `0`，不自动检测证书。
我再想想怎么处理。

**Comment by tcwilliy** [comment]
10:07:22 W 导入证书时发生错误：OSError('exception: access violation reading 0x000000000A9B3880',)
10:07:22 W 导入证书时发生错误：OSError('exception: access violation reading 0x000000000A9B2DF0',)
10:07:22 W install root certificate failed, Please run as administrator/root/sudo
10:07:23 T [Find GAE] ==================== 开始查找 GAE IP ====================

**Comment by tcwilliy** [comment]
设置为0，网页会报错不是私密连接

**Comment by SeaHOH** [comment]
我也不太清楚你那里为什么无法正常导入证书，只能混略错误，让程序能正常运行。
你需要访问 http://gotox.go 导入证书。

感谢反馈。 :smile_cat:

**Comment by SeaHOH** [comment]
顺便再问一下，你的系统是？
还有右键以下方式创建的快捷键用管理员权限运行 GotoX 是否还是无法正常导入？

把这个存为 js 文件，放入根目录双击运行，会在桌面生成快捷方式。
```js
function CreateShortcut() {
    wsh = new ActiveXObject('WScript.Shell');
    link = wsh.CreateShortcut(wsh.SpecialFolders("Desktop") + '\\GotoX.lnk');
    link.TargetPath = wsh.CurrentDirectory + '\\python\\python.exe';
    link.Arguments = '..\\launcher\\win32.py';
    link.WindowStyle = 7;
    link.IconLocation = wsh.CurrentDirectory + '\\GotoX.ico';
    link.Description = 'GotoX';
    link.WorkingDirectory = wsh.CurrentDirectory + '\\python';
    link.Save();
}

function main() {
    CreateShortcut();
}

main();
```

**Comment by tcwilliy** [comment]
系统是win10 ，用3.4.3用的很正常，xxnet，mini、gop都很正常，试过用 http://gotox.go 下载并安装证书，我待会试试你这个脚本再反馈

**Comment by tcwilliy** [comment]
终于正常了 😸

**Comment by tcwilliy** [comment]
证书的报错虽然还存在，但是现在终于正常了

**Comment by SeaHOH** [comment]
就是用上面的快捷方式，右键管理员权限也无法导入吗？

**Comment by tcwilliy** [comment]
是的，我把原有的证书删除了还不行，不过现在是能用了

**Comment by SeaHOH** [comment]
知道了，谢谢。

**Comment by SeaHOH** [comment]
麻烦再帮我试一下，换了一个函数获取句柄。

**Comment by tcwilliy** [comment]
21:10:40 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000039537DD0',)
21:10:40 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000039537A90',)
21:10:40 W install root certificate failed, Please run as administrator/root/sudo
21:10:40 T 连接测试开始，超时：1750 毫秒
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 416, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 134, in get_openssl_socket
    ssl_sock.set_tlsext_host_name(server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\pyOpenSSL-17.0.0-cp35-win_amd64.egg\OpenSSL\SSL.py", line 1423, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\gevent-1.2.2-cp35-win_amd64.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 458, in _create_ssl_connection
    set_connect_finish(ip)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\common\__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '2607:f8b0:4005:1b::a'
Mon Jun 11 21:10:40 2018 <Greenlet at 0x1dc39959b90: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x000001DC39A09208>>(('2607:f8b0:4005:1b::a', 443), 'google_fe:443', None, <queue.Queue object at 0x000001DC3A2E22E8>, 1.75)> failed with KeyError

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 416, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 134, in get_openssl_socket
    ssl_sock.set_tlsext_host_name(server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\pyOpenSSL-17.0.0-cp35-win_amd64.egg\OpenSSL\SSL.py", line 1423, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\gevent-1.2.2-cp35-win_amd64.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 458, in _create_ssl_connection
    set_connect_finish(ip)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\common\__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '2607:f8b0:401a:24::a'
Mon Jun 11 21:10:40 2018 <Greenlet at 0x1dc39959930: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x000001DC39A09208>>(('2607:f8b0:401a:24::a', 443), 'google_fe:443', None, <queue.Queue object at 0x000001DC3A2E22E8>, 1.75)> failed with KeyError

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 416, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 134, in get_openssl_socket
    ssl_sock.set_tlsext_host_name(server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\pyOpenSSL-17.0.0-cp35-win_amd64.egg\OpenSSL\SSL.py", line 1423, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\gevent-1.2.2-cp35-win_amd64.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 458, in _create_ssl_connection
    set_connect_finish(ip)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\common\__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '2620:11a:a019:1::1e'
Mon Jun 11 21:10:40 2018 <Greenlet at 0x1dc39959cc0: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x000001DC39A09208>>(('2620:11a:a019:1::1e', 443), 'google_fe:443', None, <queue.Queue object at 0x000001DC3A2E22E8>, 1.75)> failed with KeyError

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 416, in _create_ssl_connection
    ssl_sock = self.get_ssl_socket(sock, server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 134, in get_openssl_socket
    ssl_sock.set_tlsext_host_name(server_hostname)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\pyOpenSSL-17.0.0-cp35-win_amd64.egg\OpenSSL\SSL.py", line 1423, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\python\site-packages\gevent-1.2.2-cp35-win_amd64.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 458, in _create_ssl_connection
    set_connect_finish(ip)
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\HTTPUtil.py", line 232, in set_connect_finish
    connect_limiter[ip].get()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\common\__init__.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '2620:11a:a02a::23'
Mon Jun 11 21:10:40 2018 <Greenlet at 0x1dc39959d58: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x000001DC39A09208>>(('2620:11a:a02a::23', 443), 'google_fe:443', None, <queue.Queue object at 0x000001DC3A2E22E8>, 1.75)> failed with KeyError

**Comment by SeaHOH** [comment]
换了还是出错，算了，就这样了。
不过第二个 TypeError 不应该啊，没看出是为什么。

**Comment by SeaHOH** [comment]
哦，看出来了，马上改。。。

**Comment by SeaHOH** [comment]
52bcf52fe83716748ca81a4f615fa5b189476ce2
这条忘记引用了

**Comment by tcwilliy** [comment]
额，引用这条52bcf52，这完全没法用了
Traceback (most recent call last):
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\start.py", line 14, in <module>
    proxy.main()
  File "F:\Free\GOA\GotoX-3.4.4-cp35-win_amd64\local\proxy.py", line 263, in main
    CertUtil.check_ca()
AttributeError: module 'local.CertUtil' has no attribute 'check_ca'

**Comment by tcwilliy** [comment]
搞错了，不好意思

**Comment by tcwilliy** [comment]
证书那个错误还在，可以用了，1080没一点问题

**Comment by SeaHOH** [comment]
嗯嗯，IPv6 还是很好用的。

**Comment by tcwilliy** [comment]
为啥xx-net的goa那么慢呢？  和你这个gotox真的没法比啊，比gop的php还慢，不知为啥

**Comment by SeaHOH** [comment]
IP 选择策略考虑的因素侧重不一样。
